version: 2

seeds:
  - name: location_enrichment
    description: >
      Lookup table berisi informasi detail lokasi seperti alamat, kota, dan koordinat geografis.
    columns:
      - name: location_id
        description: Primary key lokasi
        tests:
          - not_null
          - unique

      - name: location_name
        description: Nama lokasi

      - name: address
        description: Alamat lengkap

      - name: city
        description: Nama kota

      - name: state
        description: Nama provinsi atau negara bagian

      - name: zip_code
        description: Kode pos

      - name: latitude
        description: Koordinat lintang (latitude) lokasi

      - name: longitude
        description: Koordinat bujur (longitude) lokasi